In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
ev = np.array([1,3])

arr = np.array([
    [1, -1],
    [6, -4]
])

In [8]:
eig_val_arr, eig_vec_arr = np.linalg.eig(arr)
np.linalg.eig(arr)

(array([-1., -2.]),
 array([[0.4472136 , 0.31622777],
        [0.89442719, 0.9486833 ]]))

In [9]:
#Convert ev into unit vector and compare with 'np.linalg.eig(arr)' result
ev/np.linalg.norm(ev)

array([0.31622777, 0.9486833 ])

In [10]:
#conversion values match with result's 2nd column. Thus, eigenvalue is located at 'eig_val_arr' index 1
#Eigenvalue
eig_val_arr[1]

-2.0